<?php declare(strict_types=1);
//session_start();

require_once 'pagee.php';


class LandAusgabe extends pagee{
    protected function __construct()
    {
        parent::__construct();
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    protected function getViewData(): array{
        $flughafen =array();
        session_start();
        var_dump($_SESSION);
        $landUebergabe ="Italien";
        if(isset($_SESSION['neuland'])) {
            $landUebergabe = $_SESSION['neuland'];
            var_dump($_SESSION);
            echo "<br>$landUebergabe</br>";
        }

        $sql = "Select Zielflughafen, Land FROM reisebuero.zielflughafen WHERE Land = '$landUebergabe'";
        $result = $this->_database->query($sql);

        if($result->num_rows > 0){
            while($row =$result->fetch_assoc()){
                $flughafen[] = $row;
            }
        }else{
            echo "Attribute bzw. Klassen nicht gefunden";
        }

        $result->free();
        return $flughafen;
    }
    protected function generateView()
    {

        $array = $this->getViewData();

        $this->generatePageHeader('LandAusgabe');
        echo <<< EOT
<table><tr><th>Zielflughafen</th><th>Land</th></tr>
EOT;


        foreach ($array as $row) {
            $zielf= $row['Zielflughafen'];
            $land = $row['Land'];
            echo <<<EOT
<tr>
  <td>$zielf</td>
  <td>$land</td>
</tr>
EOT;
        }


        echo <<<EOT
</table>
EOT;

        //alles löschen, was in SESSION steht.

        $this->generatePageFooter();
    }





    public static function main():void{
        try{
            $landAusgabe = new LandAusgabe();
            $landAusgabe->generateView();

        }catch (EXception $e){
            header("Content-Typwe: text/html; charset=UTF-8");
            echo $e->getMessage();
        }
    }
}
//session_destroy();

LandAusgabe::main();
?>